# Spike Mixture Train

In [27]:
import numpy as np
import math

In [38]:
# define time scale
t = 10 #lets say seconds

# define firing rates (say per second) of latent variables (we will use these to initialise poisson processes)
v = [0.1,0.5,2]
lat = [] #an array of arrays for each of the latent variables

#realise poisson processes with given rates
for i in range(len(v)):
    lat.append([]) #create a new array for the latent variable

    ti = np.random.exponential(v[i]) #time of first spike    
    while ti < t: 
        lat[i].append(ti)
        ti += np.random.exponential(v[i]) #determine next spike by sampling from exponential distribution with given r



In [40]:
# write a function to take a list of times and fits them into discrete time bins
dt = 0.1
n = math.ceil(t/dt)

def get_pos(time):
    return math.floor(time/dt) #rounds down so if spike happened in time [0.00, 0.01), it will be mapped to position 0

def fit_to_discr(spikes):
    discr = np.zeros(n)
    for spike_time in spikes:
        i = get_pos(spike_time)
        discr[i] = 1
    return discr


In [41]:
fit_to_discr(lat[2])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# w(i,j) is the probability of neuron i firing given that latent variable j fires
W = np.array([[0.2,0.3,0.8],
              [0.5,0.3,0.5],
              [0.3,0.5,0.2]])

From the latent processes, determine how many spikes to choose using random binomial generation, then randomly sample that many spikes from each of the poisson realisations. The list of spike times in the visible neurons need not be sorted since the `fit_to_discr` function does not things to be sorted in time. 

In [9]:
steps = 5
#for i in range(steps):
l = np.random.binomial(1,v) #which latent variables spike
print(l) 

p = W*(np.ones((3,1)) @ l.T) #cond probs that neurons spike given latent variables spike
print(p)

n = np.sum(np.random.binomial(1,p),axis=0) #see whether neurons fire given latent spikes
print(n)

[[0]
 [0]
 [1]]
[[0.  0.  0.8]
 [0.  0.  0.5]
 [0.  0.  0.2]]
[0 0 1]
